version: '3.8'
services:
  db:
    image: postgres:12
    command: ["postgres", "-c", "fsync=false", "-c", "full_page_writes=off"]
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: biblioteca_pessoal_development
    ports:
      - "5432:5432"
    expose: 
      - "5432"

  app:
    build: 
      context: .
      dockerfile: ./docker/app/Dockerfile
    command: bash -c "bundle exec puma -C config/puma.rb"
    volumes:
      - .:/aplicacao
    depends_on:
      - db 
  
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - app
    ports:
      - 80:80