name: "Integração Contínua"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: biblioteca_pessoal_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/biblioteca_pessoal_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: '3.0.0'
      - name: Install Bundle
        run: |
          cd aplicacao/
          bundle install
      - name: Set up database schema
        run: |
          rails db:create
          rails db:migrate
          rails db:seed
      
  test:
    needs: build
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: biblioteca_pessoal_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/biblioteca_pessoal_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: '3.0.0'
      - name: Install Bundle
        run: |
          cd aplicacao/
          bundle install
      # Add or replace database setup steps here
      - name: Set up database schema
        run: rails db:reset
      # Add or replace test runners here
      - name: Run tests
        run: rspec

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.0.0
      # Add or replace any other lints here
      - name: Install Bundle
        run: |
          cd aplicacao/
          bundle install
      - name: Install Gems
        run: |
          gem install bundler-audit 
          gem install brakeman 
          gem install rubocop 
      - name: Security audit dependencies
        run: |
          cd aplicacao/
          bundler-audit --update
      - name: Security audit application code
        run: |
         cd aplicacao/
         brakeman -q -w2
      - name: Lint Ruby files
        run: |
          cd aplicacao/
          rubocop --lint

  push_to_registry:
    needs: [lint, test]
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: giovanadionisio/gces_trabalho-individual-2021-2

      - name: Build and push Docker app image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: aplicacao
          file: aplicacao/docker/app/Dockerfile
          push: true
          tags: giovanadionisio/gces_trabalho-individual-2021-2-app:app-0.0
      
      - name: Build and push Docker web image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: aplicacao
          file: aplicacao/docker/web/Dockerfile
          push: true
          tags: giovanadionisio/gces_trabalho-individual-2021-2-web:web-0.0
