name: "Integração Contínua"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: biblioteca_pessoal_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/biblioteca_pessoal_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: '3.0.0'
      - name: Install Bundle
        run: |
          cd aplicacao/
          bundle install
      - name: Set up database schema
        run: |
          rails db:create
          rails db:migrate
          rails db:seed
      
  test:
    needs: build
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: biblioteca_pessoal_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/biblioteca_pessoal_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: '3.0.0'
      - name: Install Bundle
        run: |
          cd aplicacao/
          bundle install
      # Add or replace database setup steps here
      - name: Set up database schema
        run: rails db:reset
      # Add or replace test runners here
      - name: Run tests
        run: rspec

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.0.0
      # Add or replace any other lints here
      - name: Install Bundle
        run: |
          cd aplicacao/
          bundle install
      - name: Install Gems
        run: |
          gem install bundler-audit 
          gem install brakeman 
          gem install rubocop 
      - name: Security audit dependencies
        run: |
          cd aplicacao/
          bundler-audit --update
      - name: Security audit application code
        run: |
         cd aplicacao/
         brakeman -q -w2
      - name: Lint Ruby files
        run: |
          cd aplicacao/
          rubocop --lint